export const PERMISSIONS = {
  trabajador: {
    proyectos: ['read'],
    Consulta_Archivo_T_cnico: ['read'],
  },
  asociado: {
    proyectos: ['read', 'create', 'update'],
    clientes: ['read', 'create', 'update'],
    cartas: ['read', 'create', 'update', 'delete'],
    proveedores: ['read', 'create', 'update'],
    // contratos: ['read', 'create'],
    Consulta_Archivo_T_cnico: ['read'],
    archivoAdministrativo: ['read'],
  },
  secretaria: {
    proyectos: ['read'],
    clientes: ['read'],
    cartas: ['read', 'create', 'update', 'delete'],
    // remitentes: ['read'],
    archivoAdministrativo: ['read', 'create', 'update'],
    revistas: ['read'],
    libros: ['read'],
    Consulta_Archivo_T_cnico: ['read'],
  },
  administracion: {
    clientes: ['read', 'create', 'update'],
    // facturas: ['read', 'create', 'update'],
    // contratos: ['read', 'create', 'update'],
    proveedores: ['read', 'create'],
    proyectos: ['read'],
    cartas: ['read'],
    archivoAdministrativo: ['read'],
    trabajadores: ['read'],
    fotos: ['read'],
    revistas: ['read'],
    libros: ['read'],
    Consulta_Archivo_T_cnico: ['read'],
  },
  admin: {
    proyectos: ['read', 'create', 'update', 'delete'],
    clientes: ['read', 'create', 'update', 'delete'],
    cartas: ['read', 'create', 'update', 'delete'],
    proveedores: ['read', 'create', 'update', 'delete'],
    archivoAdministrativo: ['read', 'create', 'update', 'delete'],
    trabajadores: ['read', 'create', 'update', 'delete'],
    fotos: ['read', 'create', 'update', 'delete'],
    revistas: ['read', 'create', 'update', 'delete'],
    libros: ['read', 'create', 'update', 'delete'],
    Consulta_Archivo_T_cnico: ['read', 'create', 'update', 'delete']

  },
};
