export const campoPrisma = {
  proyectos: {
    Numero_Expediente:     { campo: "Numero_Expediente", tipo: "string" },
    Palabras_clave:        { campo: "Palabras_clave", tipo: "string" },
    Proyecto:              { campo: "Proyecto", tipo: "string" },
    Arquitecto:            { campo: "Arquitecto", tipo: "string" },
    m2_construidos_suelo:  { campo: "m2_construidos_suelo", tipo: "string" },
    techo_edificable:      { campo: "techo_edificable", tipo: "string" },
    m2_sotano:             { campo: "m2_sotano", tipo: "string" },
    numero_viviendas:      { campo: "numero_viviendas", tipo: "float" },
    Fecha_Visado:          { campo: "Fecha_Visado", tipo: "string" },
    Fecha_Inicio:          { campo: "Fecha_Inicio", tipo: "string" },
    N_Expediente_Colegio:  { campo: "N_Expediente_Colegio", tipo: "string" },
    Localidad:             { campo: "Localidad", tipo: "string" },
    Promotor:              { campo: "Promotor", tipo: "string" },
    N__Cliente:            { campo: "N__Cliente", tipo: "int" },
    Tipo_de_proyecto:      { campo: "Tipo_de_proyecto", tipo: "string" },
    categoria:             { campo: "categoria", tipo: "string" },
    uso:                   { campo: "uso", tipo: "string" },
    situacion:             { campo: "situacion", tipo: "string" },
    Tramitacion:           { campo: "Tramitacion", tipo: "string" },
    instancias:            { campo: "instancias", tipo: "string" },
    ruta_carpeta:          { campo: "ruta_carpeta", tipo: "string" },
    id_cliente:            { campo: "id_cliente", tipo: "int" },
    pasillo:               { campo: "pasillo", tipo: "int" },
    columna:               { campo: "columna", tipo: "int" },
    valda:                 { campo: "valda", tipo: "int" },
    ParteLetras:           { campo: "ParteLetras", tipo: "string" },
  },

  cartas: {
    NumeroExpediente: { campo: "NumeroExpediente", tipo: "string" },
    Asunto:           { campo: "Asunto", tipo: "string" },
    Fecha:            { campo: "Fecha", tipo: "date" },
    Empresa:          { campo: "Empresa", tipo: "string" },
    Destinatario:     { campo: "Destinatario", tipo: "string" },
    TipoDeSoporte:    { campo: "TipoDeSoporte", tipo: "string" },
    ModoDeEnvio:      { campo: "ModoDeEnvio", tipo: "string" },
    Departamento:     { campo: "Departamento", tipo: "string" },
    Remitente:        { campo: "Remitente", tipo: "string" },
    NumeroCliente:    { campo: "NumeroCliente", tipo: "int" },
    PDF:              { campo: "PDF", tipo: "bytes" },
    NumeroRegistro:   { campo: "NumeroRegistro", tipo: "int" },
  },

  clientes: {
    id_cliente: { campo: "id_cliente", tipo: "int" },
    Grupo:      { campo: "Grupo", tipo: "string" },
    Codigo:     { campo: "Codigo", tipo: "string" },
    Nombre:     { campo: "Nombre", tipo: "string" },
    Nif:        { campo: "Nif", tipo: "string" },
  },
};
